repos:
  - repo: local
    hooks:
      - id: no-commit-master
        name: no-commit-master
        entry: bash -c 'if test $(git rev-parse --abbrev-ref HEAD) = "master"; then  echo "Cannot commit on master"; exit 1; fi'
        language: system

      - id: go-fmt
        name: go-fmt
        entry: .hooks/go-fmt.sh
        types: [go]
        language: system

      - id: go-fumpt
        name: go-fumpt
        entry: .hooks/go-fumpt.sh
        types: [go]
        language: system

      - id: go-critic
        name: go-critic
        entry: .hooks/go-critic.sh
        types: [go]
        language: system

      - id: go-vet
        name: go-vet
        entry: .hooks/go-vet.sh
        types: [go]
        language: system

      - id: go-cyclo
        name: go-cyclo
        entry: .hooks/go-cyclo.sh
        args: [-over=20]
        types: [go]
        language: system

      - id: go-mod-tidy
        name: go-mod-tidy
        entry: .hooks/go-mod-tidy.sh
        args: [-over=20]
        types: [go]
        language: system

      - id: go-sec
        name: go-sec
        entry: .hooks/go-sec.sh
        types: [go]
        language: system

      - id: go-structslop
        name: go-structslop
        entry: .hooks/go-structslop.sh
        types: [go]
        language: system

  # Generic pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
